module.exports = [
  {
    date: "April 1",
    from: "Employer",
    name: "Income",
    amount: 1000,
    category: "Income",
  },
  {
    date: "April 1",
    from: "Tax Preparer",
    name: "Taxes",
    amount: -300,
    category: "Important Expense",
  },
  {
    date: "April 1",
    from: "Employer",
    name: "Retirement",
    amount: -200,
    category: "Savings",
  },
  {
    date: "April 1",
    from: "Bank",
    name: "Savings",
    amount: -100,
    category: "Savings",
  },
  {
    date: "April 1",
    from: "Checking Account",
    name: "Credit Card Payment",
    amount: -100,
    category: "Credit Cards",
  },
  {
    date: "April 5",
    from: "Aunt Tilda",
    name: "Monthly Birthday Money From Aunt Tilda",
    amount: 20,
    category: "Income",
  },
  {
    date: "April 5",
    from: "Starbucks",
    name: "Coffee",
    amount: -4,
    category: "Food",
  },
  {
    date: "April 5",
    from: "Verizon",
    name: "Internet",
    amount: -100,
    category: "Home Maintenance",
  },
  {
    date: "April 3",
    from: "Grocery Store",
    name: "Groceries",
    amount: -76,
    category: "Food",
  },
  {
    date: "April 3",
    from: "Pet Store",
    name: "Pet Food",
    amount: -7,
    category: "Pets",
  },
];
